export interface Service {
  id: string;
  name: string;
  category: string;
  description: string;
  startingPrice: number;
  rating: number;
  reviewCount: number;
  duration: string;
  image: string;
  popular: boolean;
}

export interface Provider {
  id: string;
  name: string;
  avatar: string;
  rating: number;
  reviewCount: number;
  jobsCompleted: number;
  specializations: string[];
  experience: string;
  verified: boolean;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  color: string;
  bgColor: string;
  serviceCount: number;
}

export interface Booking {
  id: string;
  serviceId: string;
  serviceName: string;
  providerName: string;
  providerAvatar: string;
  date: string;
  time: string;
  status: "upcoming" | "completed" | "cancelled";
  price: number;
  address: string;
  rating?: number;
}

export const CATEGORIES: Category[] = [
  {
    id: "cleaning",
    name: "Cleaning",
    icon: "wind",
    color: "#3b82f6",
    bgColor: "#dbeafe",
    serviceCount: 13,
  },
  {
    id: "plumbing",
    name: "Plumbing",
    icon: "droplet",
    color: "#06b6d4",
    bgColor: "#cffafe",
    serviceCount: 10,
  },
  {
    id: "electrical",
    name: "Electrical",
    icon: "zap",
    color: "#f59e0b",
    bgColor: "#fef3c7",
    serviceCount: 11,
  },
  {
    id: "salon-women",
    name: "Salon for Women",
    icon: "scissors",
    color: "#ec4899",
    bgColor: "#fce7f3",
    serviceCount: 18,
  },
  {
    id: "salon-men",
    name: "Salon for Men",
    icon: "user",
    color: "#0ea5e9",
    bgColor: "#e0f2fe",
    serviceCount: 7,
  },
  {
    id: "massage",
    name: "Massage & Spa",
    icon: "heart",
    color: "#f43f5e",
    bgColor: "#ffe4e6",
    serviceCount: 6,
  },
  {
    id: "painting",
    name: "Painting",
    icon: "edit-3",
    color: "#8b5cf6",
    bgColor: "#ede9fe",
    serviceCount: 6,
  },
  {
    id: "pest",
    name: "Pest Control",
    icon: "shield",
    color: "#10b981",
    bgColor: "#d1fae5",
    serviceCount: 8,
  },
  {
    id: "carpentry",
    name: "Carpentry",
    icon: "tool",
    color: "#d97706",
    bgColor: "#fde68a",
    serviceCount: 8,
  },
  {
    id: "appliances",
    name: "Appliance Repair",
    icon: "cpu",
    color: "#6366f1",
    bgColor: "#e0e7ff",
    serviceCount: 13,
  },
  {
    id: "water-purifier",
    name: "Water Purifier",
    icon: "droplet",
    color: "#0891b2",
    bgColor: "#cffafe",
    serviceCount: 5,
  },
];

export const SERVICES: Service[] = [
  // ── Cleaning (13) ──────────────────────────────────────────────────────────
  {
    id: "c1",
    name: "Home Deep Cleaning 1BHK",
    category: "cleaning",
    description: "Complete deep cleaning of a 1BHK home including kitchen, bathroom, bedroom and living area using eco-friendly products.",
    startingPrice: 1199,
    rating: 4.8,
    reviewCount: 3142,
    duration: "3-4 hours",
    image: "cleaning",
    popular: true,
  },
  {
    id: "c2",
    name: "Home Deep Cleaning 2BHK",
    category: "cleaning",
    description: "Thorough deep cleaning of a 2BHK home. Covers all rooms, kitchen appliances, bathroom tiles and floor scrubbing.",
    startingPrice: 1839,
    rating: 4.8,
    reviewCount: 2561,
    duration: "4-5 hours",
    image: "cleaning",
    popular: true,
  },
  {
    id: "c3",
    name: "Home Deep Cleaning 3BHK",
    category: "cleaning",
    description: "End-to-end deep cleaning of a 3BHK home by a team of trained professionals with industrial-grade equipment.",
    startingPrice: 2559,
    rating: 4.7,
    reviewCount: 1874,
    duration: "5-6 hours",
    image: "cleaning",
    popular: false,
  },
  {
    id: "c4",
    name: "Bathroom Cleaning (Single)",
    category: "cleaning",
    description: "Deep cleaning and sanitization of a single bathroom — tiles, fixtures, toilet, basin and floor scrubbed spotless.",
    startingPrice: 319,
    rating: 4.7,
    reviewCount: 2104,
    duration: "1-2 hours",
    image: "cleaning",
    popular: false,
  },
  {
    id: "c5",
    name: "Bathroom Cleaning (2 Bathrooms)",
    category: "cleaning",
    description: "Deep cleaning and sanitization of two bathrooms. Includes tile scrubbing, descaling and full disinfection.",
    startingPrice: 519,
    rating: 4.7,
    reviewCount: 1432,
    duration: "2-3 hours",
    image: "cleaning",
    popular: false,
  },
  {
    id: "c6",
    name: "Kitchen Deep Cleaning",
    category: "cleaning",
    description: "Professional deep cleaning of your kitchen including chimney, hob, sink, tiles, and all appliances exterior.",
    startingPrice: 599,
    rating: 4.8,
    reviewCount: 1987,
    duration: "1.5-2 hours",
    image: "cleaning",
    popular: true,
  },
  {
    id: "c7",
    name: "Sofa Cleaning (2-Seater)",
    category: "cleaning",
    description: "Steam cleaning and stain removal for a 2-seater sofa. Removes dust, allergens and embedded dirt.",
    startingPrice: 679,
    rating: 4.6,
    reviewCount: 1123,
    duration: "1-2 hours",
    image: "cleaning",
    popular: false,
  },
  {
    id: "c8",
    name: "Sofa Cleaning (3-Seater)",
    category: "cleaning",
    description: "Steam cleaning and stain removal for a 3-seater sofa. Leaves fabric fresh, sanitized and odour-free.",
    startingPrice: 799,
    rating: 4.6,
    reviewCount: 987,
    duration: "1.5-2 hours",
    image: "cleaning",
    popular: false,
  },
  {
    id: "c9",
    name: "Carpet Cleaning (Per Carpet)",
    category: "cleaning",
    description: "Deep carpet cleaning using hot water extraction. Removes stains, dust mites and embedded grime.",
    startingPrice: 439,
    rating: 4.7,
    reviewCount: 743,
    duration: "1-2 hours",
    image: "cleaning",
    popular: false,
  },
  {
    id: "c10",
    name: "Mattress Cleaning (Single)",
    category: "cleaning",
    description: "UV vacuuming and sanitization of a single mattress. Kills dust mites and removes allergens for a healthier sleep.",
    startingPrice: 399,
    rating: 4.7,
    reviewCount: 654,
    duration: "1-1.5 hours",
    image: "cleaning",
    popular: false,
  },
  {
    id: "c11",
    name: "Balcony Cleaning",
    category: "cleaning",
    description: "Complete balcony scrubbing including floor, grills and walls. Removes stains, moss and accumulated dirt.",
    startingPrice: 279,
    rating: 4.6,
    reviewCount: 521,
    duration: "1-2 hours",
    image: "cleaning",
    popular: false,
  },
  {
    id: "c12",
    name: "Water Tank Cleaning",
    category: "cleaning",
    description: "Professional cleaning and disinfection of overhead or underground water tanks. Ensures safe, clean water supply.",
    startingPrice: 639,
    rating: 4.8,
    reviewCount: 892,
    duration: "2-3 hours",
    image: "cleaning",
    popular: false,
  },
  {
    id: "c13",
    name: "Office Deep Cleaning",
    category: "cleaning",
    description: "Comprehensive deep cleaning for offices including workstations, washrooms, pantry and all common areas.",
    startingPrice: 1599,
    rating: 4.7,
    reviewCount: 432,
    duration: "4-6 hours",
    image: "cleaning",
    popular: false,
  },

  // ── Plumbing (10) ──────────────────────────────────────────────────────────
  {
    id: "p1",
    name: "Tap Installation / Repair",
    category: "plumbing",
    description: "Installation or repair of kitchen and bathroom taps. Fixes drips, leaks and worn-out washers quickly.",
    startingPrice: 159,
    rating: 4.8,
    reviewCount: 1876,
    duration: "30-60 min",
    image: "plumbing",
    popular: true,
  },
  {
    id: "p2",
    name: "Pipe Leak Repair",
    category: "plumbing",
    description: "Expert diagnosis and repair of pipe leaks including concealed pipes, supply lines and waste pipes.",
    startingPrice: 279,
    rating: 4.9,
    reviewCount: 1245,
    duration: "1-2 hours",
    image: "plumbing",
    popular: true,
  },
  {
    id: "p3",
    name: "Drain Cleaning",
    category: "plumbing",
    description: "Professional unblocking of kitchen, bathroom or outdoor drains using high-pressure jet equipment.",
    startingPrice: 399,
    rating: 4.6,
    reviewCount: 876,
    duration: "1-2 hours",
    image: "plumbing",
    popular: false,
  },
  {
    id: "p4",
    name: "Geyser Repair",
    category: "plumbing",
    description: "Diagnosis and repair of geyser faults including heating element, thermostat and pressure valve issues.",
    startingPrice: 399,
    rating: 4.8,
    reviewCount: 731,
    duration: "1-2 hours",
    image: "plumbing",
    popular: true,
  },
  {
    id: "p5",
    name: "Geyser Installation",
    category: "plumbing",
    description: "Safe installation of new geysers with proper plumbing and electrical connections by certified technicians.",
    startingPrice: 599,
    rating: 4.7,
    reviewCount: 512,
    duration: "1-2 hours",
    image: "plumbing",
    popular: false,
  },
  {
    id: "p6",
    name: "Flush Tank Repair",
    category: "plumbing",
    description: "Repair of wall-mounted or concealed flush tanks. Fixes float valve, flush button and internal mechanism.",
    startingPrice: 239,
    rating: 4.7,
    reviewCount: 643,
    duration: "30-60 min",
    image: "plumbing",
    popular: false,
  },
  {
    id: "p7",
    name: "Basin / Sink Installation",
    category: "plumbing",
    description: "Installation of wash basins, kitchen sinks and vanity units with waste pipe fittings and sealing.",
    startingPrice: 399,
    rating: 4.7,
    reviewCount: 389,
    duration: "1-2 hours",
    image: "plumbing",
    popular: false,
  },
  {
    id: "p8",
    name: "Shower Installation",
    category: "plumbing",
    description: "Professional installation of overhead showers, hand showers and shower enclosures with leak-free fittings.",
    startingPrice: 479,
    rating: 4.8,
    reviewCount: 421,
    duration: "1-2 hours",
    image: "plumbing",
    popular: false,
  },
  {
    id: "p9",
    name: "Toilet Seat Repair",
    category: "plumbing",
    description: "Replacement or repair of toilet seats and covers. Covers all standard and wall-hung toilet models.",
    startingPrice: 319,
    rating: 4.6,
    reviewCount: 298,
    duration: "30-60 min",
    image: "plumbing",
    popular: false,
  },
  {
    id: "p10",
    name: "Water Meter Installation",
    category: "plumbing",
    description: "Installation and testing of domestic water meters to accurately track consumption and detect leaks.",
    startingPrice: 239,
    rating: 4.6,
    reviewCount: 187,
    duration: "1 hour",
    image: "plumbing",
    popular: false,
  },

  // ── Electrical (11) ────────────────────────────────────────────────────────
  {
    id: "e1",
    name: "Fan Installation",
    category: "electrical",
    description: "Professional installation of ceiling fans, wall fans and exhaust fans with proper wiring and balancing.",
    startingPrice: 199,
    rating: 4.9,
    reviewCount: 3201,
    duration: "30-60 min",
    image: "electrical",
    popular: true,
  },
  {
    id: "e2",
    name: "Fan Repair",
    category: "electrical",
    description: "Diagnosis and repair of ceiling and wall fans — covers capacitor, winding, regulator and bearing issues.",
    startingPrice: 199,
    rating: 4.8,
    reviewCount: 1876,
    duration: "30-60 min",
    image: "electrical",
    popular: false,
  },
  {
    id: "e3",
    name: "Light Fitting",
    category: "electrical",
    description: "Installation of ceiling lights, LED panels, tube lights and decorative fittings with safe wiring.",
    startingPrice: 119,
    rating: 4.8,
    reviewCount: 2145,
    duration: "30-45 min",
    image: "electrical",
    popular: true,
  },
  {
    id: "e4",
    name: "Switch & Socket Repair",
    category: "electrical",
    description: "Safe replacement and repair of switches, sockets and modular boards using ISI-certified components.",
    startingPrice: 119,
    rating: 4.8,
    reviewCount: 2087,
    duration: "30-45 min",
    image: "electrical",
    popular: true,
  },
  {
    id: "e5",
    name: "MCB / Fuse Repair",
    category: "electrical",
    description: "Repair or replacement of MCBs, fuse boxes and distribution boards to restore safe power supply.",
    startingPrice: 159,
    rating: 4.8,
    reviewCount: 987,
    duration: "30-60 min",
    image: "electrical",
    popular: false,
  },
  {
    id: "e6",
    name: "Geyser Wiring",
    category: "electrical",
    description: "Dedicated wiring and earthing for geysers and water heaters as per electrical safety standards.",
    startingPrice: 279,
    rating: 4.7,
    reviewCount: 543,
    duration: "1-2 hours",
    image: "electrical",
    popular: false,
  },
  {
    id: "e7",
    name: "AC Wiring",
    category: "electrical",
    description: "Dedicated AC power circuit installation including wiring, earthing, isolator and safety checks.",
    startingPrice: 479,
    rating: 4.8,
    reviewCount: 712,
    duration: "1-2 hours",
    image: "electrical",
    popular: false,
  },
  {
    id: "e8",
    name: "Inverter & Battery Installation",
    category: "electrical",
    description: "Installation of home inverters and batteries with proper wiring, earthing and load balancing.",
    startingPrice: 559,
    rating: 4.7,
    reviewCount: 634,
    duration: "1-2 hours",
    image: "electrical",
    popular: false,
  },
  {
    id: "e9",
    name: "Full Electrical Wiring",
    category: "electrical",
    description: "Complete new room or renovation wiring including conduit fitting, wiring, board installation and testing.",
    startingPrice: 799,
    rating: 4.8,
    reviewCount: 543,
    duration: "2-4 hours",
    image: "electrical",
    popular: false,
  },
  {
    id: "e10",
    name: "Doorbell Installation",
    category: "electrical",
    description: "Installation of wired or wireless doorbells and video door phones with proper fitting and wiring.",
    startingPrice: 159,
    rating: 4.7,
    reviewCount: 421,
    duration: "30-45 min",
    image: "electrical",
    popular: false,
  },
  {
    id: "e11",
    name: "CCTV Installation (2 Cameras)",
    category: "electrical",
    description: "Installation of 2 CCTV cameras with DVR, cabling and remote viewing setup for home security.",
    startingPrice: 1199,
    rating: 4.8,
    reviewCount: 876,
    duration: "2-3 hours",
    image: "electrical",
    popular: true,
  },

  // ── Salon for Women (18) ───────────────────────────────────────────────────
  {
    id: "sw1",
    name: "Haircut & Styling",
    category: "salon-women",
    description: "Professional women's haircut and styling by certified beauticians at your home. Trim, shape and blow-dry included.",
    startingPrice: 359,
    rating: 4.8,
    reviewCount: 4532,
    duration: "1-2 hours",
    image: "salon",
    popular: true,
  },
  {
    id: "sw2",
    name: "Hair Wash & Blow Dry",
    category: "salon-women",
    description: "Relaxing hair wash with premium shampoo and conditioner followed by a professional blow-dry and finish.",
    startingPrice: 279,
    rating: 4.7,
    reviewCount: 2341,
    duration: "45-60 min",
    image: "salon",
    popular: false,
  },
  {
    id: "sw3",
    name: "Hair Spa",
    category: "salon-women",
    description: "Deep conditioning hair spa treatment to repair damage, add shine and nourish hair from root to tip.",
    startingPrice: 639,
    rating: 4.8,
    reviewCount: 1876,
    duration: "1-1.5 hours",
    image: "salon",
    popular: true,
  },
  {
    id: "sw4",
    name: "Hair Color (Global)",
    category: "salon-women",
    description: "Full global hair color service using professional-grade dyes. Covers roots to tips with even, rich color.",
    startingPrice: 1279,
    rating: 4.7,
    reviewCount: 1432,
    duration: "2-3 hours",
    image: "salon",
    popular: false,
  },
  {
    id: "sw5",
    name: "Hair Highlights",
    category: "salon-women",
    description: "Expert highlighting service with foils for natural-looking dimension and color contrast.",
    startingPrice: 1039,
    rating: 4.7,
    reviewCount: 987,
    duration: "2-3 hours",
    image: "salon",
    popular: false,
  },
  {
    id: "sw6",
    name: "Keratin Treatment",
    category: "salon-women",
    description: "Professional keratin smoothing treatment to eliminate frizz, add shine and make hair manageable for months.",
    startingPrice: 2399,
    rating: 4.8,
    reviewCount: 654,
    duration: "2-3 hours",
    image: "salon",
    popular: false,
  },
  {
    id: "sw7",
    name: "Facial (Basic)",
    category: "salon-women",
    description: "Basic cleansing facial with steam, exfoliation, mask and toning. Refreshes and brightens dull skin.",
    startingPrice: 559,
    rating: 4.8,
    reviewCount: 2198,
    duration: "1 hour",
    image: "salon",
    popular: true,
  },
  {
    id: "sw8",
    name: "Facial (Premium)",
    category: "salon-women",
    description: "Premium facial with advanced serums, massage and luxury masks tailored to your skin type.",
    startingPrice: 799,
    rating: 4.9,
    reviewCount: 1543,
    duration: "1-1.5 hours",
    image: "salon",
    popular: false,
  },
  {
    id: "sw9",
    name: "Cleanup",
    category: "salon-women",
    description: "Quick skin cleanup service including cleansing, scrubbing, steam and toning for an instant glow.",
    startingPrice: 359,
    rating: 4.7,
    reviewCount: 1876,
    duration: "45-60 min",
    image: "salon",
    popular: true,
  },
  {
    id: "sw10",
    name: "Full Arms Waxing",
    category: "salon-women",
    description: "Smooth and long-lasting full arm waxing using premium wax. Leaves skin silky and hair-free.",
    startingPrice: 239,
    rating: 4.6,
    reviewCount: 2341,
    duration: "30-45 min",
    image: "salon",
    popular: false,
  },
  {
    id: "sw11",
    name: "Full Legs Waxing",
    category: "salon-women",
    description: "Full leg waxing for smooth, hair-free skin. Uses warm or cold wax based on your preference.",
    startingPrice: 279,
    rating: 4.6,
    reviewCount: 1987,
    duration: "45-60 min",
    image: "salon",
    popular: false,
  },
  {
    id: "sw12",
    name: "Full Body Waxing",
    category: "salon-women",
    description: "Complete full body waxing by expert beauticians in a comfortable, private home setting.",
    startingPrice: 799,
    rating: 4.7,
    reviewCount: 1123,
    duration: "1.5-2 hours",
    image: "salon",
    popular: false,
  },
  {
    id: "sw13",
    name: "Eyebrow Threading",
    category: "salon-women",
    description: "Precise eyebrow shaping through professional threading. Defines arches and removes unwanted hair.",
    startingPrice: 79,
    rating: 4.7,
    reviewCount: 3214,
    duration: "15-20 min",
    image: "salon",
    popular: true,
  },
  {
    id: "sw14",
    name: "Manicure",
    category: "salon-women",
    description: "Complete manicure including nail filing, cuticle care, hand massage, buffing and nail polish.",
    startingPrice: 399,
    rating: 4.7,
    reviewCount: 1765,
    duration: "45-60 min",
    image: "salon",
    popular: false,
  },
  {
    id: "sw15",
    name: "Pedicure",
    category: "salon-women",
    description: "Relaxing pedicure with foot soak, scrubbing, nail care, foot massage and nail polish.",
    startingPrice: 479,
    rating: 4.7,
    reviewCount: 1543,
    duration: "45-60 min",
    image: "salon",
    popular: false,
  },
  {
    id: "sw16",
    name: "Bridal Makeup",
    category: "salon-women",
    description: "Stunning bridal makeup by experienced artists. Includes trial, HD makeup, false lashes and setting spray.",
    startingPrice: 3999,
    rating: 4.9,
    reviewCount: 876,
    duration: "3-4 hours",
    image: "salon",
    popular: true,
  },
  {
    id: "sw17",
    name: "Party Makeup",
    category: "salon-women",
    description: "Glamorous party makeup with long-lasting products. Perfect for events, festivals and celebrations.",
    startingPrice: 1439,
    rating: 4.8,
    reviewCount: 1234,
    duration: "1.5-2 hours",
    image: "salon",
    popular: false,
  },
  {
    id: "sw18",
    name: "Detan (Face & Neck)",
    category: "salon-women",
    description: "Skin detan treatment for face and neck using de-pigmentation products to restore natural skin tone.",
    startingPrice: 359,
    rating: 4.7,
    reviewCount: 987,
    duration: "30-45 min",
    image: "salon",
    popular: false,
  },

  // ── Salon for Men (7) ──────────────────────────────────────────────────────
  {
    id: "sm1",
    name: "Haircut",
    category: "salon-men",
    description: "Stylish men's haircut at home by expert barbers. Includes wash, cut and styling to your preference.",
    startingPrice: 239,
    rating: 4.8,
    reviewCount: 2876,
    duration: "30-45 min",
    image: "salon",
    popular: true,
  },
  {
    id: "sm2",
    name: "Beard Trim & Grooming",
    category: "salon-men",
    description: "Professional beard shaping, trimming and grooming for a sharp, well-defined look.",
    startingPrice: 119,
    rating: 4.8,
    reviewCount: 2143,
    duration: "20-30 min",
    image: "salon",
    popular: true,
  },
  {
    id: "sm3",
    name: "Hair Color",
    category: "salon-men",
    description: "Men's hair color service covering grey coverage, highlights or fashion colors using quality dyes.",
    startingPrice: 479,
    rating: 4.7,
    reviewCount: 765,
    duration: "1-2 hours",
    image: "salon",
    popular: false,
  },
  {
    id: "sm4",
    name: "Facial",
    category: "salon-men",
    description: "Men's deep cleansing facial with steam, scrub, mask and toning for healthy, clear skin.",
    startingPrice: 479,
    rating: 4.7,
    reviewCount: 1087,
    duration: "1-1.5 hours",
    image: "salon",
    popular: false,
  },
  {
    id: "sm5",
    name: "Head Massage",
    category: "salon-men",
    description: "Relaxing head and scalp massage with warm oil to relieve stress, improve circulation and promote hair growth.",
    startingPrice: 279,
    rating: 4.8,
    reviewCount: 1432,
    duration: "30-45 min",
    image: "salon",
    popular: true,
  },
  {
    id: "sm6",
    name: "Detan (Face)",
    category: "salon-men",
    description: "Men's face detan treatment to remove tan lines and even out skin tone using skin-safe formulations.",
    startingPrice: 319,
    rating: 4.6,
    reviewCount: 654,
    duration: "30-45 min",
    image: "salon",
    popular: false,
  },
  {
    id: "sm7",
    name: "Ear & Nose Wax",
    category: "salon-men",
    description: "Safe and hygienic ear and nose hair removal using professional warm wax for clean grooming.",
    startingPrice: 119,
    rating: 4.6,
    reviewCount: 432,
    duration: "15-20 min",
    image: "salon",
    popular: false,
  },

  // ── Massage & Spa (6) ──────────────────────────────────────────────────────
  {
    id: "ms1",
    name: "Full Body Relaxation Massage",
    category: "massage",
    description: "60-minute full body Swedish relaxation massage at home. Eases muscle tension, stress and fatigue.",
    startingPrice: 999,
    rating: 4.9,
    reviewCount: 1543,
    duration: "60 min",
    image: "cleaning",
    popular: true,
  },
  {
    id: "ms2",
    name: "Deep Tissue Massage",
    category: "massage",
    description: "60-minute deep tissue massage targeting chronic muscle knots and tension in the back, shoulders and neck.",
    startingPrice: 1199,
    rating: 4.9,
    reviewCount: 1234,
    duration: "60 min",
    image: "cleaning",
    popular: true,
  },
  {
    id: "ms3",
    name: "Swedish Massage (90 min)",
    category: "massage",
    description: "90-minute premium Swedish massage for full-body relaxation using aromatic oils and long, flowing strokes.",
    startingPrice: 1439,
    rating: 4.9,
    reviewCount: 876,
    duration: "90 min",
    image: "cleaning",
    popular: false,
  },
  {
    id: "ms4",
    name: "Head & Shoulder Massage",
    category: "massage",
    description: "30-minute targeted massage for head, neck and shoulders to relieve headaches, stiffness and stress.",
    startingPrice: 479,
    rating: 4.8,
    reviewCount: 1087,
    duration: "30 min",
    image: "cleaning",
    popular: false,
  },
  {
    id: "ms5",
    name: "Foot Reflexology",
    category: "massage",
    description: "30-minute reflexology session targeting pressure points on the feet to relieve pain and improve wellbeing.",
    startingPrice: 479,
    rating: 4.8,
    reviewCount: 765,
    duration: "30 min",
    image: "cleaning",
    popular: false,
  },
  {
    id: "ms6",
    name: "Couple Massage",
    category: "massage",
    description: "60-minute relaxation massage for two people simultaneously by two therapists in the comfort of your home.",
    startingPrice: 1999,
    rating: 4.9,
    reviewCount: 543,
    duration: "60 min",
    image: "cleaning",
    popular: false,
  },

  // ── Painting (6) ───────────────────────────────────────────────────────────
  {
    id: "pt1",
    name: "Interior Wall Painting",
    category: "painting",
    description: "Professional interior wall painting with premium quality paints. Includes surface preparation and two coats.",
    startingPrice: 1599,
    rating: 4.6,
    reviewCount: 891,
    duration: "1-2 days",
    image: "painting",
    popular: true,
  },
  {
    id: "pt2",
    name: "Exterior Painting",
    category: "painting",
    description: "Durable exterior house painting using weather-resistant paints. Includes primer, two coats and touch-ups.",
    startingPrice: 3199,
    rating: 4.6,
    reviewCount: 432,
    duration: "2-4 days",
    image: "painting",
    popular: false,
  },
  {
    id: "pt3",
    name: "Wood Polishing",
    category: "painting",
    description: "Professional wood polishing and varnishing for doors, windows and furniture to restore natural beauty.",
    startingPrice: 1199,
    rating: 4.7,
    reviewCount: 543,
    duration: "1-2 days",
    image: "painting",
    popular: false,
  },
  {
    id: "pt4",
    name: "Waterproofing",
    category: "painting",
    description: "Expert waterproofing of terrace, bathroom and external walls to permanently stop seepage and leakage.",
    startingPrice: 2399,
    rating: 4.7,
    reviewCount: 456,
    duration: "1-2 days",
    image: "painting",
    popular: false,
  },
  {
    id: "pt5",
    name: "Wall Texture / Design",
    category: "painting",
    description: "Decorative wall texture and designer finishes including Venetian plaster, sand texture and stencil work.",
    startingPrice: 1599,
    rating: 4.7,
    reviewCount: 312,
    duration: "1-2 days",
    image: "painting",
    popular: false,
  },
  {
    id: "pt6",
    name: "Whitewash",
    category: "painting",
    description: "Traditional whitewash for interior and exterior walls. Fresh, clean look with lime-based coating.",
    startingPrice: 799,
    rating: 4.5,
    reviewCount: 287,
    duration: "1 day",
    image: "painting",
    popular: false,
  },

  // ── Pest Control (8) ───────────────────────────────────────────────────────
  {
    id: "pc1",
    name: "Cockroach Control",
    category: "pest",
    description: "Safe gel-based cockroach treatment that is child and pet friendly. Eliminates cockroaches within 72 hours.",
    startingPrice: 799,
    rating: 4.7,
    reviewCount: 1567,
    duration: "1-2 hours",
    image: "pest",
    popular: true,
  },
  {
    id: "pc2",
    name: "Bed Bug Treatment",
    category: "pest",
    description: "Comprehensive bed bug heat and chemical treatment. Targets all life stages for complete elimination.",
    startingPrice: 1599,
    rating: 4.8,
    reviewCount: 823,
    duration: "2-3 hours",
    image: "pest",
    popular: false,
  },
  {
    id: "pc3",
    name: "Termite Control (Pre-construction)",
    category: "pest",
    description: "Chemical soil treatment barrier for pre-construction termite proofing of foundations and slabs.",
    startingPrice: 1999,
    rating: 4.8,
    reviewCount: 312,
    duration: "2-4 hours",
    image: "pest",
    popular: false,
  },
  {
    id: "pc4",
    name: "Termite Control (Post-construction)",
    category: "pest",
    description: "Post-construction anti-termite treatment using drilling and chemical injection to protect wooden structures.",
    startingPrice: 1599,
    rating: 4.8,
    reviewCount: 456,
    duration: "2-4 hours",
    image: "pest",
    popular: false,
  },
  {
    id: "pc5",
    name: "Mosquito Control",
    category: "pest",
    description: "Fogging and residual spray treatment to eliminate mosquitoes and prevent breeding in and around your home.",
    startingPrice: 999,
    rating: 4.6,
    reviewCount: 987,
    duration: "1-2 hours",
    image: "pest",
    popular: true,
  },
  {
    id: "pc6",
    name: "Rodent / Rat Control",
    category: "pest",
    description: "Safe rodent control using bait stations and traps. Includes entry-point sealing recommendations.",
    startingPrice: 1199,
    rating: 4.7,
    reviewCount: 543,
    duration: "2-3 hours",
    image: "pest",
    popular: false,
  },
  {
    id: "pc7",
    name: "General Pest Control",
    category: "pest",
    description: "All-in-one pest control treatment covering ants, spiders, silverfish and common household insects.",
    startingPrice: 1199,
    rating: 4.7,
    reviewCount: 765,
    duration: "2-3 hours",
    image: "pest",
    popular: false,
  },
  {
    id: "pc8",
    name: "Lizard Control",
    category: "pest",
    description: "Effective lizard repellent treatment applied to walls and entry points to keep lizards away.",
    startingPrice: 799,
    rating: 4.5,
    reviewCount: 321,
    duration: "1-2 hours",
    image: "pest",
    popular: false,
  },

  // ── Carpentry (8) ──────────────────────────────────────────────────────────
  {
    id: "cp1",
    name: "Furniture Assembly",
    category: "carpentry",
    description: "Professional assembly of flat-pack and modular furniture. All tools included, no mess left behind.",
    startingPrice: 279,
    rating: 4.8,
    reviewCount: 1234,
    duration: "1-2 hours",
    image: "carpentry",
    popular: true,
  },
  {
    id: "cp2",
    name: "Furniture Repair",
    category: "carpentry",
    description: "Expert repair of wooden furniture including joints, hinges, drawers and structural damage.",
    startingPrice: 399,
    rating: 4.7,
    reviewCount: 643,
    duration: "1-2 hours",
    image: "carpentry",
    popular: false,
  },
  {
    id: "cp3",
    name: "Door Repair / Fitting",
    category: "carpentry",
    description: "Repair and fitting of wooden and flush doors. Fixes sagging, squeaking, broken hinges and faulty locks.",
    startingPrice: 359,
    rating: 4.7,
    reviewCount: 876,
    duration: "1-2 hours",
    image: "carpentry",
    popular: true,
  },
  {
    id: "cp4",
    name: "Window Repair",
    category: "carpentry",
    description: "Repair of wooden and aluminium windows including frame, pane, hinges and sealing for weatherproofing.",
    startingPrice: 319,
    rating: 4.6,
    reviewCount: 432,
    duration: "1-2 hours",
    image: "carpentry",
    popular: false,
  },
  {
    id: "cp5",
    name: "Wardrobe Installation",
    category: "carpentry",
    description: "Installation of modular or hinged wardrobes with precise fitting, shelf placement and door alignment.",
    startingPrice: 799,
    rating: 4.8,
    reviewCount: 543,
    duration: "2-4 hours",
    image: "carpentry",
    popular: false,
  },
  {
    id: "cp6",
    name: "Bed Repair",
    category: "carpentry",
    description: "Repair of wooden bed frames including broken slats, loose joints, headboard and storage mechanisms.",
    startingPrice: 479,
    rating: 4.7,
    reviewCount: 321,
    duration: "1-2 hours",
    image: "carpentry",
    popular: false,
  },
  {
    id: "cp7",
    name: "Wood Polishing (Furniture)",
    category: "carpentry",
    description: "Restore furniture shine with professional wood polishing, sanding and lacquer or PU finish application.",
    startingPrice: 639,
    rating: 4.7,
    reviewCount: 456,
    duration: "2-3 hours",
    image: "carpentry",
    popular: false,
  },
  {
    id: "cp8",
    name: "Sofa Frame Repair",
    category: "carpentry",
    description: "Structural repair of wooden sofa frames including broken legs, sagging base and joint reinforcement.",
    startingPrice: 559,
    rating: 4.7,
    reviewCount: 287,
    duration: "1-2 hours",
    image: "carpentry",
    popular: false,
  },

  // ── Appliance Repair (13) ──────────────────────────────────────────────────
  {
    id: "ar1",
    name: "AC Service (1 Ton)",
    category: "appliances",
    description: "Complete service for 1-ton AC including cleaning filters, coils, drainage and performance check.",
    startingPrice: 679,
    rating: 4.8,
    reviewCount: 2341,
    duration: "1-2 hours",
    image: "appliances",
    popular: true,
  },
  {
    id: "ar2",
    name: "AC Service (1.5 Ton)",
    category: "appliances",
    description: "Complete service for 1.5-ton AC including deep cleaning, gas pressure check and cooling optimization.",
    startingPrice: 799,
    rating: 4.8,
    reviewCount: 1987,
    duration: "1-2 hours",
    image: "appliances",
    popular: true,
  },
  {
    id: "ar3",
    name: "AC Gas Refill",
    category: "appliances",
    description: "AC refrigerant gas refill with leak check. Restores full cooling capacity and energy efficiency.",
    startingPrice: 1199,
    rating: 4.7,
    reviewCount: 1234,
    duration: "1-2 hours",
    image: "appliances",
    popular: false,
  },
  {
    id: "ar4",
    name: "AC Installation (1-1.5 Ton)",
    category: "appliances",
    description: "Professional split AC installation including bracket, copper pipe, drainage and electrical connections.",
    startingPrice: 1279,
    rating: 4.8,
    reviewCount: 876,
    duration: "2-3 hours",
    image: "appliances",
    popular: false,
  },
  {
    id: "ar5",
    name: "Washing Machine Repair",
    category: "appliances",
    description: "Expert repair of all washing machine brands. Covers motor, drum, board, door latch and valve issues.",
    startingPrice: 399,
    rating: 4.7,
    reviewCount: 1234,
    duration: "1-2 hours",
    image: "appliances",
    popular: true,
  },
  {
    id: "ar6",
    name: "Refrigerator Repair",
    category: "appliances",
    description: "Diagnosis and repair of all fridge brands. Covers compressor, thermostat, fan, door seal and gas issues.",
    startingPrice: 439,
    rating: 4.7,
    reviewCount: 987,
    duration: "1-2 hours",
    image: "appliances",
    popular: false,
  },
  {
    id: "ar7",
    name: "Microwave Repair",
    category: "appliances",
    description: "Repair of microwave ovens covering magnetron, turntable, door latch and control board faults.",
    startingPrice: 359,
    rating: 4.6,
    reviewCount: 654,
    duration: "30-60 min",
    image: "appliances",
    popular: false,
  },
  {
    id: "ar8",
    name: "TV Repair",
    category: "appliances",
    description: "Diagnosis and repair of LED, LCD and Smart TVs. Covers screen, board, backlight and HDMI port issues.",
    startingPrice: 479,
    rating: 4.6,
    reviewCount: 765,
    duration: "1-2 hours",
    image: "appliances",
    popular: false,
  },
  {
    id: "ar9",
    name: "Geyser Repair",
    category: "appliances",
    description: "Repair of electric and gas geysers covering heating element, thermostat, valve and pilot light issues.",
    startingPrice: 399,
    rating: 4.7,
    reviewCount: 543,
    duration: "1-2 hours",
    image: "appliances",
    popular: false,
  },
  {
    id: "ar10",
    name: "Dishwasher Repair",
    category: "appliances",
    description: "Repair of all dishwasher brands covering pump, spray arm, door latch, control board and drainage.",
    startingPrice: 439,
    rating: 4.6,
    reviewCount: 312,
    duration: "1-2 hours",
    image: "appliances",
    popular: false,
  },
  {
    id: "ar11",
    name: "Chimney Cleaning & Repair",
    category: "appliances",
    description: "Deep cleaning of kitchen chimneys including filter, motor and duct. Restores full suction power.",
    startingPrice: 479,
    rating: 4.7,
    reviewCount: 876,
    duration: "1-2 hours",
    image: "appliances",
    popular: true,
  },
  {
    id: "ar12",
    name: "Treadmill Repair",
    category: "appliances",
    description: "Repair and servicing of treadmills covering belt, motor, console and incline mechanism issues.",
    startingPrice: 559,
    rating: 4.6,
    reviewCount: 234,
    duration: "1-2 hours",
    image: "appliances",
    popular: false,
  },
  {
    id: "ar13",
    name: "Inverter / UPS Repair",
    category: "appliances",
    description: "Diagnosis and repair of home inverters and UPS units covering battery, board and charging faults.",
    startingPrice: 399,
    rating: 4.7,
    reviewCount: 432,
    duration: "1-2 hours",
    image: "appliances",
    popular: false,
  },

  // ── Water Purifier / RO (5) ────────────────────────────────────────────────
  {
    id: "ro1",
    name: "RO Service & Filter Change",
    category: "water-purifier",
    description: "Comprehensive RO service including membrane check, all filter replacements and water quality testing.",
    startingPrice: 399,
    rating: 4.8,
    reviewCount: 1543,
    duration: "1-2 hours",
    image: "plumbing",
    popular: true,
  },
  {
    id: "ro2",
    name: "RO Installation",
    category: "water-purifier",
    description: "Professional under-sink or wall-mount RO purifier installation with proper plumbing and testing.",
    startingPrice: 679,
    rating: 4.8,
    reviewCount: 876,
    duration: "1-2 hours",
    image: "plumbing",
    popular: true,
  },
  {
    id: "ro3",
    name: "RO Repair",
    category: "water-purifier",
    description: "Diagnosis and repair of RO purifier faults including pump, membrane, solenoid valve and TDS issues.",
    startingPrice: 359,
    rating: 4.7,
    reviewCount: 654,
    duration: "1-2 hours",
    image: "plumbing",
    popular: false,
  },
  {
    id: "ro4",
    name: "UV Purifier Service",
    category: "water-purifier",
    description: "Servicing of UV water purifiers including UV lamp replacement, filter cleaning and disinfection.",
    startingPrice: 319,
    rating: 4.7,
    reviewCount: 432,
    duration: "1 hour",
    image: "plumbing",
    popular: false,
  },
  {
    id: "ro5",
    name: "Water Softener Service",
    category: "water-purifier",
    description: "Maintenance and servicing of water softeners including resin regeneration, valve check and salt refill.",
    startingPrice: 479,
    rating: 4.6,
    reviewCount: 198,
    duration: "1-2 hours",
    image: "plumbing",
    popular: false,
  },
];

export const PROVIDERS: Provider[] = [
  {
    id: "p1",
    name: "Rahul Sharma",
    avatar: "RS",
    rating: 4.9,
    reviewCount: 342,
    jobsCompleted: 1256,
    specializations: ["Deep Cleaning", "Office Cleaning", "Move-in Cleaning"],
    experience: "5 years",
    verified: true,
  },
  {
    id: "p2",
    name: "Priya Patel",
    avatar: "PP",
    rating: 4.8,
    reviewCount: 289,
    jobsCompleted: 987,
    specializations: ["Haircut", "Facial", "Manicure"],
    experience: "4 years",
    verified: true,
  },
  {
    id: "p3",
    name: "Amit Kumar",
    avatar: "AK",
    rating: 4.9,
    reviewCount: 412,
    jobsCompleted: 1589,
    specializations: ["Pipe Repair", "Drain Cleaning", "Bathroom Fitting"],
    experience: "7 years",
    verified: true,
  },
  {
    id: "p4",
    name: "Sunita Devi",
    avatar: "SD",
    rating: 4.7,
    reviewCount: 178,
    jobsCompleted: 634,
    specializations: ["Home Cleaning", "Kitchen Deep Clean"],
    experience: "3 years",
    verified: true,
  },
  {
    id: "p5",
    name: "Vikram Singh",
    avatar: "VS",
    rating: 4.8,
    reviewCount: 267,
    jobsCompleted: 892,
    specializations: ["Wiring", "Fan Installation", "Switch Repair"],
    experience: "6 years",
    verified: true,
  },
];

export const BOOKINGS: Booking[] = [
  {
    id: "b1",
    serviceId: "c1",
    serviceName: "Home Deep Cleaning 1BHK",
    providerName: "Rahul Sharma",
    providerAvatar: "RS",
    date: "2026-04-15",
    time: "10:00 AM",
    status: "upcoming",
    price: 1199,
    address: "123 MG Road, Bangalore 560001",
  },
  {
    id: "b2",
    serviceId: "sw1",
    serviceName: "Haircut & Styling",
    providerName: "Priya Patel",
    providerAvatar: "PP",
    date: "2026-04-12",
    time: "2:00 PM",
    status: "upcoming",
    price: 359,
    address: "45 Koramangala, Bangalore 560034",
  },
  {
    id: "b3",
    serviceId: "p2",
    serviceName: "Pipe Leak Repair",
    providerName: "Amit Kumar",
    providerAvatar: "AK",
    date: "2026-04-01",
    time: "11:00 AM",
    status: "completed",
    price: 279,
    address: "78 Indiranagar, Bangalore 560038",
    rating: 5,
  },
  {
    id: "b4",
    serviceId: "e1",
    serviceName: "Fan Installation",
    providerName: "Vikram Singh",
    providerAvatar: "VS",
    date: "2026-03-28",
    time: "9:00 AM",
    status: "completed",
    price: 199,
    address: "123 MG Road, Bangalore 560001",
    rating: 4,
  },
];
