import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Award,
  Bell,
  BellOff,
  Briefcase,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  Clock,
  Cpu,
  CreditCard,
  Crosshair,
  DollarSign,
  Droplet,
  Edit3,
  FileText,
  Hash,
  Heart,
  HelpCircle,
  Home,
  Inbox,
  Info,
  LayoutGrid,
  LogOut,
  MapPin,
  Navigation,
  Pencil,
  Phone,
  Plus,
  Radio,
  RefreshCw,
  Scissors,
  Search,
  Shield,
  Star,
  Tag,
  TrendingUp,
  Upload,
  User,
  Users,
  WifiOff,
  Wind,
  Wrench,
  X,
  Zap,
} from "lucide-react-native";
import React from "react";

const iconMap = {
  "alert-circle": AlertCircle,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  award: Award,
  bell: Bell,
  "bell-off": BellOff,
  briefcase: Briefcase,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  "check-circle": CheckCircle,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  clock: Clock,
  cpu: Cpu,
  "credit-card": CreditCard,
  crosshair: Crosshair,
  "dollar-sign": DollarSign,
  droplet: Droplet,
  "edit-2": Pencil,
  "edit-3": Edit3,
  "file-text": FileText,
  grid: LayoutGrid,
  hash: Hash,
  heart: Heart,
  "help-circle": HelpCircle,
  home: Home,
  inbox: Inbox,
  info: Info,
  "log-out": LogOut,
  "map-pin": MapPin,
  navigation: Navigation,
  phone: Phone,
  plus: Plus,
  radio: Radio,
  "refresh-cw": RefreshCw,
  scissors: Scissors,
  search: Search,
  shield: Shield,
  star: Star,
  tag: Tag,
  tool: Wrench,
  "trending-up": TrendingUp,
  upload: Upload,
  user: User,
  users: Users,
  "wifi-off": WifiOff,
  wind: Wind,
  x: X,
  zap: Zap,
} as const;

type IconName = keyof typeof iconMap;

export type IconProps = {
  name: IconName | string;
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: object;
};

export function Icon({ name, size = 24, color = "#000", strokeWidth = 2 }: IconProps) {
  const LucideIcon = iconMap[name as IconName];
  if (!LucideIcon) return null;
  return <LucideIcon size={size} color={color} strokeWidth={strokeWidth} />;
}
