import { db, servicesTable, providersTable, notificationsTable } from "@workspace/db";
import { eq, sql } from "drizzle-orm";
import { logger } from "./logger";
import { USER_ID } from "./constants";

const SERVICES = [
  // ── Cleaning (13) ──────────────────────────────────────────────────────────
  {
    slug: "home-deep-cleaning-1bhk",
    name: "Home Deep Cleaning 1BHK",
    category: "cleaning",
    description: "Complete deep cleaning of a 1BHK home including kitchen, bathroom, bedroom and living area using eco-friendly products.",
    startingPrice: 1199,
    rating: 4.8,
    reviewCount: 3142,
    duration: "3-4 hours",
    imageKey: "cleaning",
    popular: true,
  },
  {
    slug: "home-deep-cleaning-2bhk",
    name: "Home Deep Cleaning 2BHK",
    category: "cleaning",
    description: "Thorough deep cleaning of a 2BHK home. Covers all rooms, kitchen appliances, bathroom tiles and floor scrubbing.",
    startingPrice: 1839,
    rating: 4.8,
    reviewCount: 2561,
    duration: "4-5 hours",
    imageKey: "cleaning",
    popular: true,
  },
  {
    slug: "home-deep-cleaning-3bhk",
    name: "Home Deep Cleaning 3BHK",
    category: "cleaning",
    description: "End-to-end deep cleaning of a 3BHK home by a team of trained professionals with industrial-grade equipment.",
    startingPrice: 2559,
    rating: 4.7,
    reviewCount: 1874,
    duration: "5-6 hours",
    imageKey: "cleaning",
    popular: false,
  },
  {
    slug: "bathroom-cleaning-single",
    name: "Bathroom Cleaning (Single)",
    category: "cleaning",
    description: "Deep cleaning and sanitization of a single bathroom — tiles, fixtures, toilet, basin and floor scrubbed spotless.",
    startingPrice: 319,
    rating: 4.7,
    reviewCount: 2104,
    duration: "1-2 hours",
    imageKey: "cleaning",
    popular: false,
  },
  {
    slug: "bathroom-cleaning-2",
    name: "Bathroom Cleaning (2 Bathrooms)",
    category: "cleaning",
    description: "Deep cleaning and sanitization of two bathrooms. Includes tile scrubbing, descaling and full disinfection.",
    startingPrice: 519,
    rating: 4.7,
    reviewCount: 1432,
    duration: "2-3 hours",
    imageKey: "cleaning",
    popular: false,
  },
  {
    slug: "kitchen-deep-cleaning",
    name: "Kitchen Deep Cleaning",
    category: "cleaning",
    description: "Professional deep cleaning of your kitchen including chimney, hob, sink, tiles, and all appliances exterior.",
    startingPrice: 599,
    rating: 4.8,
    reviewCount: 1987,
    duration: "1.5-2 hours",
    imageKey: "cleaning",
    popular: true,
  },
  {
    slug: "sofa-cleaning-2-seater",
    name: "Sofa Cleaning (2-Seater)",
    category: "cleaning",
    description: "Steam cleaning and stain removal for a 2-seater sofa. Removes dust, allergens and embedded dirt.",
    startingPrice: 679,
    rating: 4.6,
    reviewCount: 1123,
    duration: "1-2 hours",
    imageKey: "cleaning",
    popular: false,
  },
  {
    slug: "sofa-cleaning-3-seater",
    name: "Sofa Cleaning (3-Seater)",
    category: "cleaning",
    description: "Steam cleaning and stain removal for a 3-seater sofa. Leaves fabric fresh, sanitized and odour-free.",
    startingPrice: 799,
    rating: 4.6,
    reviewCount: 987,
    duration: "1.5-2 hours",
    imageKey: "cleaning",
    popular: false,
  },
  {
    slug: "carpet-cleaning",
    name: "Carpet Cleaning (Per Carpet)",
    category: "cleaning",
    description: "Deep carpet cleaning using hot water extraction. Removes stains, dust mites and embedded grime.",
    startingPrice: 439,
    rating: 4.7,
    reviewCount: 743,
    duration: "1-2 hours",
    imageKey: "cleaning",
    popular: false,
  },
  {
    slug: "mattress-cleaning",
    name: "Mattress Cleaning (Single)",
    category: "cleaning",
    description: "UV vacuuming and sanitization of a single mattress. Kills dust mites and removes allergens for a healthier sleep.",
    startingPrice: 399,
    rating: 4.7,
    reviewCount: 654,
    duration: "1-1.5 hours",
    imageKey: "cleaning",
    popular: false,
  },
  {
    slug: "balcony-cleaning",
    name: "Balcony Cleaning",
    category: "cleaning",
    description: "Complete balcony scrubbing including floor, grills and walls. Removes stains, moss and accumulated dirt.",
    startingPrice: 279,
    rating: 4.6,
    reviewCount: 521,
    duration: "1-2 hours",
    imageKey: "cleaning",
    popular: false,
  },
  {
    slug: "water-tank-cleaning",
    name: "Water Tank Cleaning",
    category: "cleaning",
    description: "Professional cleaning and disinfection of overhead or underground water tanks. Ensures safe, clean water supply.",
    startingPrice: 639,
    rating: 4.8,
    reviewCount: 892,
    duration: "2-3 hours",
    imageKey: "cleaning",
    popular: false,
  },
  {
    slug: "office-deep-cleaning",
    name: "Office Deep Cleaning",
    category: "cleaning",
    description: "Comprehensive deep cleaning for offices including workstations, washrooms, pantry and all common areas.",
    startingPrice: 1599,
    rating: 4.7,
    reviewCount: 432,
    duration: "4-6 hours",
    imageKey: "cleaning",
    popular: false,
  },

  // ── Plumbing (10) ──────────────────────────────────────────────────────────
  {
    slug: "tap-installation-repair",
    name: "Tap Installation / Repair",
    category: "plumbing",
    description: "Installation or repair of kitchen and bathroom taps. Fixes drips, leaks and worn-out washers quickly.",
    startingPrice: 159,
    rating: 4.8,
    reviewCount: 1876,
    duration: "30-60 min",
    imageKey: "plumbing",
    popular: true,
  },
  {
    slug: "pipe-leak-repair",
    name: "Pipe Leak Repair",
    category: "plumbing",
    description: "Expert diagnosis and repair of pipe leaks including concealed pipes, supply lines and waste pipes.",
    startingPrice: 279,
    rating: 4.9,
    reviewCount: 1245,
    duration: "1-2 hours",
    imageKey: "plumbing",
    popular: true,
  },
  {
    slug: "drain-cleaning",
    name: "Drain Cleaning",
    category: "plumbing",
    description: "Professional unblocking of kitchen, bathroom or outdoor drains using high-pressure jet equipment.",
    startingPrice: 399,
    rating: 4.6,
    reviewCount: 876,
    duration: "1-2 hours",
    imageKey: "plumbing",
    popular: false,
  },
  {
    slug: "geyser-repair",
    name: "Geyser Repair",
    category: "plumbing",
    description: "Diagnosis and repair of geyser faults including heating element, thermostat and pressure valve issues.",
    startingPrice: 399,
    rating: 4.8,
    reviewCount: 731,
    duration: "1-2 hours",
    imageKey: "plumbing",
    popular: true,
  },
  {
    slug: "geyser-installation",
    name: "Geyser Installation",
    category: "plumbing",
    description: "Safe installation of new geysers with proper plumbing and electrical connections by certified technicians.",
    startingPrice: 599,
    rating: 4.7,
    reviewCount: 512,
    duration: "1-2 hours",
    imageKey: "plumbing",
    popular: false,
  },
  {
    slug: "flush-tank-repair",
    name: "Flush Tank Repair",
    category: "plumbing",
    description: "Repair of wall-mounted or concealed flush tanks. Fixes float valve, flush button and internal mechanism.",
    startingPrice: 239,
    rating: 4.7,
    reviewCount: 643,
    duration: "30-60 min",
    imageKey: "plumbing",
    popular: false,
  },
  {
    slug: "basin-sink-installation",
    name: "Basin / Sink Installation",
    category: "plumbing",
    description: "Installation of wash basins, kitchen sinks and vanity units with waste pipe fittings and sealing.",
    startingPrice: 399,
    rating: 4.7,
    reviewCount: 389,
    duration: "1-2 hours",
    imageKey: "plumbing",
    popular: false,
  },
  {
    slug: "shower-installation",
    name: "Shower Installation",
    category: "plumbing",
    description: "Professional installation of overhead showers, hand showers and shower enclosures with leak-free fittings.",
    startingPrice: 479,
    rating: 4.8,
    reviewCount: 421,
    duration: "1-2 hours",
    imageKey: "plumbing",
    popular: false,
  },
  {
    slug: "toilet-seat-repair",
    name: "Toilet Seat Repair",
    category: "plumbing",
    description: "Replacement or repair of toilet seats and covers. Covers all standard and wall-hung toilet models.",
    startingPrice: 319,
    rating: 4.6,
    reviewCount: 298,
    duration: "30-60 min",
    imageKey: "plumbing",
    popular: false,
  },
  {
    slug: "water-meter-installation",
    name: "Water Meter Installation",
    category: "plumbing",
    description: "Installation and testing of domestic water meters to accurately track consumption and detect leaks.",
    startingPrice: 239,
    rating: 4.6,
    reviewCount: 187,
    duration: "1 hour",
    imageKey: "plumbing",
    popular: false,
  },

  // ── Electrical (11) ────────────────────────────────────────────────────────
  {
    slug: "fan-installation",
    name: "Fan Installation",
    category: "electrical",
    description: "Professional installation of ceiling fans, wall fans and exhaust fans with proper wiring and balancing.",
    startingPrice: 199,
    rating: 4.9,
    reviewCount: 3201,
    duration: "30-60 min",
    imageKey: "electrical",
    popular: true,
  },
  {
    slug: "fan-repair",
    name: "Fan Repair",
    category: "electrical",
    description: "Diagnosis and repair of ceiling and wall fans — covers capacitor, winding, regulator and bearing issues.",
    startingPrice: 199,
    rating: 4.8,
    reviewCount: 1876,
    duration: "30-60 min",
    imageKey: "electrical",
    popular: false,
  },
  {
    slug: "light-fitting",
    name: "Light Fitting",
    category: "electrical",
    description: "Installation of ceiling lights, LED panels, tube lights and decorative fittings with safe wiring.",
    startingPrice: 119,
    rating: 4.8,
    reviewCount: 2145,
    duration: "30-45 min",
    imageKey: "electrical",
    popular: true,
  },
  {
    slug: "switch-socket-repair",
    name: "Switch & Socket Repair",
    category: "electrical",
    description: "Safe replacement and repair of switches, sockets and modular boards using ISI-certified components.",
    startingPrice: 119,
    rating: 4.8,
    reviewCount: 2087,
    duration: "30-45 min",
    imageKey: "electrical",
    popular: true,
  },
  {
    slug: "mcb-fuse-repair",
    name: "MCB / Fuse Repair",
    category: "electrical",
    description: "Repair or replacement of MCBs, fuse boxes and distribution boards to restore safe power supply.",
    startingPrice: 159,
    rating: 4.8,
    reviewCount: 987,
    duration: "30-60 min",
    imageKey: "electrical",
    popular: false,
  },
  {
    slug: "geyser-wiring",
    name: "Geyser Wiring",
    category: "electrical",
    description: "Dedicated wiring and earthing for geysers and water heaters as per electrical safety standards.",
    startingPrice: 279,
    rating: 4.7,
    reviewCount: 543,
    duration: "1-2 hours",
    imageKey: "electrical",
    popular: false,
  },
  {
    slug: "ac-wiring",
    name: "AC Wiring",
    category: "electrical",
    description: "Dedicated AC power circuit installation including wiring, earthing, isolator and safety checks.",
    startingPrice: 479,
    rating: 4.8,
    reviewCount: 712,
    duration: "1-2 hours",
    imageKey: "electrical",
    popular: false,
  },
  {
    slug: "inverter-battery-installation",
    name: "Inverter & Battery Installation",
    category: "electrical",
    description: "Installation of home inverters and batteries with proper wiring, earthing and load balancing.",
    startingPrice: 559,
    rating: 4.7,
    reviewCount: 634,
    duration: "1-2 hours",
    imageKey: "electrical",
    popular: false,
  },
  {
    slug: "full-electrical-wiring",
    name: "Full Electrical Wiring",
    category: "electrical",
    description: "Complete new room or renovation wiring including conduit fitting, wiring, board installation and testing.",
    startingPrice: 799,
    rating: 4.8,
    reviewCount: 543,
    duration: "2-4 hours",
    imageKey: "electrical",
    popular: false,
  },
  {
    slug: "doorbell-installation",
    name: "Doorbell Installation",
    category: "electrical",
    description: "Installation of wired or wireless doorbells and video door phones with proper fitting and wiring.",
    startingPrice: 159,
    rating: 4.7,
    reviewCount: 421,
    duration: "30-45 min",
    imageKey: "electrical",
    popular: false,
  },
  {
    slug: "cctv-installation",
    name: "CCTV Installation (2 Cameras)",
    category: "electrical",
    description: "Installation of 2 CCTV cameras with DVR, cabling and remote viewing setup for home security.",
    startingPrice: 1199,
    rating: 4.8,
    reviewCount: 876,
    duration: "2-3 hours",
    imageKey: "electrical",
    popular: true,
  },

  // ── Salon for Women (18) ───────────────────────────────────────────────────
  {
    slug: "women-haircut-styling",
    name: "Haircut & Styling",
    category: "salon-women",
    description: "Professional women's haircut and styling by certified beauticians at your home. Trim, shape and blow-dry included.",
    startingPrice: 359,
    rating: 4.8,
    reviewCount: 4532,
    duration: "1-2 hours",
    imageKey: "salon",
    popular: true,
  },
  {
    slug: "hair-wash-blow-dry",
    name: "Hair Wash & Blow Dry",
    category: "salon-women",
    description: "Relaxing hair wash with premium shampoo and conditioner followed by a professional blow-dry and finish.",
    startingPrice: 279,
    rating: 4.7,
    reviewCount: 2341,
    duration: "45-60 min",
    imageKey: "salon",
    popular: false,
  },
  {
    slug: "hair-spa",
    name: "Hair Spa",
    category: "salon-women",
    description: "Deep conditioning hair spa treatment to repair damage, add shine and nourish hair from root to tip.",
    startingPrice: 639,
    rating: 4.8,
    reviewCount: 1876,
    duration: "1-1.5 hours",
    imageKey: "salon",
    popular: true,
  },
  {
    slug: "hair-color-global",
    name: "Hair Color (Global)",
    category: "salon-women",
    description: "Full global hair color service using professional-grade dyes. Covers roots to tips with even, rich color.",
    startingPrice: 1279,
    rating: 4.7,
    reviewCount: 1432,
    duration: "2-3 hours",
    imageKey: "salon",
    popular: false,
  },
  {
    slug: "hair-highlights",
    name: "Hair Highlights",
    category: "salon-women",
    description: "Expert highlighting service with foils for natural-looking dimension and color contrast.",
    startingPrice: 1039,
    rating: 4.7,
    reviewCount: 987,
    duration: "2-3 hours",
    imageKey: "salon",
    popular: false,
  },
  {
    slug: "keratin-treatment",
    name: "Keratin Treatment",
    category: "salon-women",
    description: "Professional keratin smoothing treatment to eliminate frizz, add shine and make hair manageable for months.",
    startingPrice: 2399,
    rating: 4.8,
    reviewCount: 654,
    duration: "2-3 hours",
    imageKey: "salon",
    popular: false,
  },
  {
    slug: "facial-basic",
    name: "Facial (Basic)",
    category: "salon-women",
    description: "Basic cleansing facial with steam, exfoliation, mask and toning. Refreshes and brightens dull skin.",
    startingPrice: 559,
    rating: 4.8,
    reviewCount: 2198,
    duration: "1 hour",
    imageKey: "salon",
    popular: true,
  },
  {
    slug: "facial-premium",
    name: "Facial (Premium)",
    category: "salon-women",
    description: "Premium facial with advanced serums, massage and luxury masks tailored to your skin type.",
    startingPrice: 799,
    rating: 4.9,
    reviewCount: 1543,
    duration: "1-1.5 hours",
    imageKey: "salon",
    popular: false,
  },
  {
    slug: "cleanup",
    name: "Cleanup",
    category: "salon-women",
    description: "Quick skin cleanup service including cleansing, scrubbing, steam and toning for an instant glow.",
    startingPrice: 359,
    rating: 4.7,
    reviewCount: 1876,
    duration: "45-60 min",
    imageKey: "salon",
    popular: true,
  },
  {
    slug: "full-arms-waxing",
    name: "Full Arms Waxing",
    category: "salon-women",
    description: "Smooth and long-lasting full arm waxing using premium wax. Leaves skin silky and hair-free.",
    startingPrice: 239,
    rating: 4.6,
    reviewCount: 2341,
    duration: "30-45 min",
    imageKey: "salon",
    popular: false,
  },
  {
    slug: "full-legs-waxing",
    name: "Full Legs Waxing",
    category: "salon-women",
    description: "Full leg waxing for smooth, hair-free skin. Uses warm or cold wax based on your preference.",
    startingPrice: 279,
    rating: 4.6,
    reviewCount: 1987,
    duration: "45-60 min",
    imageKey: "salon",
    popular: false,
  },
  {
    slug: "full-body-waxing",
    name: "Full Body Waxing",
    category: "salon-women",
    description: "Complete full body waxing by expert beauticians in a comfortable, private home setting.",
    startingPrice: 799,
    rating: 4.7,
    reviewCount: 1123,
    duration: "1.5-2 hours",
    imageKey: "salon",
    popular: false,
  },
  {
    slug: "eyebrow-threading",
    name: "Eyebrow Threading",
    category: "salon-women",
    description: "Precise eyebrow shaping through professional threading. Defines arches and removes unwanted hair.",
    startingPrice: 79,
    rating: 4.7,
    reviewCount: 3214,
    duration: "15-20 min",
    imageKey: "salon",
    popular: true,
  },
  {
    slug: "manicure",
    name: "Manicure",
    category: "salon-women",
    description: "Complete manicure including nail filing, cuticle care, hand massage, buffing and nail polish.",
    startingPrice: 399,
    rating: 4.7,
    reviewCount: 1765,
    duration: "45-60 min",
    imageKey: "salon",
    popular: false,
  },
  {
    slug: "pedicure",
    name: "Pedicure",
    category: "salon-women",
    description: "Relaxing pedicure with foot soak, scrubbing, nail care, foot massage and nail polish.",
    startingPrice: 479,
    rating: 4.7,
    reviewCount: 1543,
    duration: "45-60 min",
    imageKey: "salon",
    popular: false,
  },
  {
    slug: "bridal-makeup",
    name: "Bridal Makeup",
    category: "salon-women",
    description: "Stunning bridal makeup by experienced artists. Includes trial, HD makeup, false lashes and setting spray.",
    startingPrice: 3999,
    rating: 4.9,
    reviewCount: 876,
    duration: "3-4 hours",
    imageKey: "salon",
    popular: true,
  },
  {
    slug: "party-makeup",
    name: "Party Makeup",
    category: "salon-women",
    description: "Glamorous party makeup with long-lasting products. Perfect for events, festivals and celebrations.",
    startingPrice: 1439,
    rating: 4.8,
    reviewCount: 1234,
    duration: "1.5-2 hours",
    imageKey: "salon",
    popular: false,
  },
  {
    slug: "detan-face-neck",
    name: "Detan (Face & Neck)",
    category: "salon-women",
    description: "Skin detan treatment for face and neck using de-pigmentation products to restore natural skin tone.",
    startingPrice: 359,
    rating: 4.7,
    reviewCount: 987,
    duration: "30-45 min",
    imageKey: "salon",
    popular: false,
  },

  // ── Salon for Men (7) ──────────────────────────────────────────────────────
  {
    slug: "men-haircut",
    name: "Haircut",
    category: "salon-men",
    description: "Stylish men's haircut at home by expert barbers. Includes wash, cut and styling to your preference.",
    startingPrice: 239,
    rating: 4.8,
    reviewCount: 2876,
    duration: "30-45 min",
    imageKey: "salon",
    popular: true,
  },
  {
    slug: "beard-trim-grooming",
    name: "Beard Trim & Grooming",
    category: "salon-men",
    description: "Professional beard shaping, trimming and grooming for a sharp, well-defined look.",
    startingPrice: 119,
    rating: 4.8,
    reviewCount: 2143,
    duration: "20-30 min",
    imageKey: "salon",
    popular: true,
  },
  {
    slug: "men-hair-color",
    name: "Hair Color",
    category: "salon-men",
    description: "Men's hair color service covering grey coverage, highlights or fashion colors using quality dyes.",
    startingPrice: 479,
    rating: 4.7,
    reviewCount: 765,
    duration: "1-2 hours",
    imageKey: "salon",
    popular: false,
  },
  {
    slug: "men-facial",
    name: "Facial",
    category: "salon-men",
    description: "Men's deep cleansing facial with steam, scrub, mask and toning for healthy, clear skin.",
    startingPrice: 479,
    rating: 4.7,
    reviewCount: 1087,
    duration: "1-1.5 hours",
    imageKey: "salon",
    popular: false,
  },
  {
    slug: "head-massage",
    name: "Head Massage",
    category: "salon-men",
    description: "Relaxing head and scalp massage with warm oil to relieve stress, improve circulation and promote hair growth.",
    startingPrice: 279,
    rating: 4.8,
    reviewCount: 1432,
    duration: "30-45 min",
    imageKey: "salon",
    popular: true,
  },
  {
    slug: "men-detan-face",
    name: "Detan (Face)",
    category: "salon-men",
    description: "Men's face detan treatment to remove tan lines and even out skin tone using skin-safe formulations.",
    startingPrice: 319,
    rating: 4.6,
    reviewCount: 654,
    duration: "30-45 min",
    imageKey: "salon",
    popular: false,
  },
  {
    slug: "ear-nose-wax",
    name: "Ear & Nose Wax",
    category: "salon-men",
    description: "Safe and hygienic ear and nose hair removal using professional warm wax for clean grooming.",
    startingPrice: 119,
    rating: 4.6,
    reviewCount: 432,
    duration: "15-20 min",
    imageKey: "salon",
    popular: false,
  },

  // ── Massage & Spa (6) ──────────────────────────────────────────────────────
  {
    slug: "full-body-relaxation-massage",
    name: "Full Body Relaxation Massage",
    category: "massage",
    description: "60-minute full body Swedish relaxation massage at home. Eases muscle tension, stress and fatigue.",
    startingPrice: 999,
    rating: 4.9,
    reviewCount: 1543,
    duration: "60 min",
    imageKey: "cleaning",
    popular: true,
  },
  {
    slug: "deep-tissue-massage",
    name: "Deep Tissue Massage",
    category: "massage",
    description: "60-minute deep tissue massage targeting chronic muscle knots and tension in the back, shoulders and neck.",
    startingPrice: 1199,
    rating: 4.9,
    reviewCount: 1234,
    duration: "60 min",
    imageKey: "cleaning",
    popular: true,
  },
  {
    slug: "swedish-massage",
    name: "Swedish Massage (90 min)",
    category: "massage",
    description: "90-minute premium Swedish massage for full-body relaxation using aromatic oils and long, flowing strokes.",
    startingPrice: 1439,
    rating: 4.9,
    reviewCount: 876,
    duration: "90 min",
    imageKey: "cleaning",
    popular: false,
  },
  {
    slug: "head-shoulder-massage",
    name: "Head & Shoulder Massage",
    category: "massage",
    description: "30-minute targeted massage for head, neck and shoulders to relieve headaches, stiffness and stress.",
    startingPrice: 479,
    rating: 4.8,
    reviewCount: 1087,
    duration: "30 min",
    imageKey: "cleaning",
    popular: false,
  },
  {
    slug: "foot-reflexology",
    name: "Foot Reflexology",
    category: "massage",
    description: "30-minute reflexology session targeting pressure points on the feet to relieve pain and improve wellbeing.",
    startingPrice: 479,
    rating: 4.8,
    reviewCount: 765,
    duration: "30 min",
    imageKey: "cleaning",
    popular: false,
  },
  {
    slug: "couple-massage",
    name: "Couple Massage",
    category: "massage",
    description: "60-minute relaxation massage for two people simultaneously by two therapists in the comfort of your home.",
    startingPrice: 1999,
    rating: 4.9,
    reviewCount: 543,
    duration: "60 min",
    imageKey: "cleaning",
    popular: false,
  },

  // ── Painting (6) ───────────────────────────────────────────────────────────
  {
    slug: "interior-wall-painting",
    name: "Interior Wall Painting",
    category: "painting",
    description: "Professional interior wall painting with premium quality paints. Includes surface preparation and two coats.",
    startingPrice: 1599,
    rating: 4.6,
    reviewCount: 891,
    duration: "1-2 days",
    imageKey: "painting",
    popular: true,
  },
  {
    slug: "exterior-painting",
    name: "Exterior Painting",
    category: "painting",
    description: "Durable exterior house painting using weather-resistant paints. Includes primer, two coats and touch-ups.",
    startingPrice: 3199,
    rating: 4.6,
    reviewCount: 432,
    duration: "2-4 days",
    imageKey: "painting",
    popular: false,
  },
  {
    slug: "wood-polishing",
    name: "Wood Polishing",
    category: "painting",
    description: "Professional wood polishing and varnishing for doors, windows and furniture to restore natural beauty.",
    startingPrice: 1199,
    rating: 4.7,
    reviewCount: 543,
    duration: "1-2 days",
    imageKey: "painting",
    popular: false,
  },
  {
    slug: "waterproofing",
    name: "Waterproofing",
    category: "painting",
    description: "Expert waterproofing of terrace, bathroom and external walls to permanently stop seepage and leakage.",
    startingPrice: 2399,
    rating: 4.7,
    reviewCount: 456,
    duration: "1-2 days",
    imageKey: "painting",
    popular: false,
  },
  {
    slug: "wall-texture-design",
    name: "Wall Texture / Design",
    category: "painting",
    description: "Decorative wall texture and designer finishes including Venetian plaster, sand texture and stencil work.",
    startingPrice: 1599,
    rating: 4.7,
    reviewCount: 312,
    duration: "1-2 days",
    imageKey: "painting",
    popular: false,
  },
  {
    slug: "whitewash",
    name: "Whitewash",
    category: "painting",
    description: "Traditional whitewash for interior and exterior walls. Fresh, clean look with lime-based coating.",
    startingPrice: 799,
    rating: 4.5,
    reviewCount: 287,
    duration: "1 day",
    imageKey: "painting",
    popular: false,
  },

  // ── Pest Control (8) ───────────────────────────────────────────────────────
  {
    slug: "cockroach-control",
    name: "Cockroach Control",
    category: "pest",
    description: "Safe gel-based cockroach treatment that is child and pet friendly. Eliminates cockroaches within 72 hours.",
    startingPrice: 799,
    rating: 4.7,
    reviewCount: 1567,
    duration: "1-2 hours",
    imageKey: "pest",
    popular: true,
  },
  {
    slug: "bed-bug-treatment",
    name: "Bed Bug Treatment",
    category: "pest",
    description: "Comprehensive bed bug heat and chemical treatment. Targets all life stages for complete elimination.",
    startingPrice: 1599,
    rating: 4.8,
    reviewCount: 823,
    duration: "2-3 hours",
    imageKey: "pest",
    popular: false,
  },
  {
    slug: "termite-control-pre",
    name: "Termite Control (Pre-construction)",
    category: "pest",
    description: "Chemical soil treatment barrier for pre-construction termite proofing of foundations and slabs.",
    startingPrice: 1999,
    rating: 4.8,
    reviewCount: 312,
    duration: "2-4 hours",
    imageKey: "pest",
    popular: false,
  },
  {
    slug: "termite-control-post",
    name: "Termite Control (Post-construction)",
    category: "pest",
    description: "Post-construction anti-termite treatment using drilling and chemical injection to protect wooden structures.",
    startingPrice: 1599,
    rating: 4.8,
    reviewCount: 456,
    duration: "2-4 hours",
    imageKey: "pest",
    popular: false,
  },
  {
    slug: "mosquito-control",
    name: "Mosquito Control",
    category: "pest",
    description: "Fogging and residual spray treatment to eliminate mosquitoes and prevent breeding in and around your home.",
    startingPrice: 999,
    rating: 4.6,
    reviewCount: 987,
    duration: "1-2 hours",
    imageKey: "pest",
    popular: true,
  },
  {
    slug: "rodent-rat-control",
    name: "Rodent / Rat Control",
    category: "pest",
    description: "Safe rodent control using bait stations and traps. Includes entry-point sealing recommendations.",
    startingPrice: 1199,
    rating: 4.7,
    reviewCount: 543,
    duration: "2-3 hours",
    imageKey: "pest",
    popular: false,
  },
  {
    slug: "general-pest-control",
    name: "General Pest Control",
    category: "pest",
    description: "All-in-one pest control treatment covering ants, spiders, silverfish and common household insects.",
    startingPrice: 1199,
    rating: 4.7,
    reviewCount: 765,
    duration: "2-3 hours",
    imageKey: "pest",
    popular: false,
  },
  {
    slug: "lizard-control",
    name: "Lizard Control",
    category: "pest",
    description: "Effective lizard repellent treatment applied to walls and entry points to keep lizards away.",
    startingPrice: 799,
    rating: 4.5,
    reviewCount: 321,
    duration: "1-2 hours",
    imageKey: "pest",
    popular: false,
  },

  // ── Carpentry (8) ──────────────────────────────────────────────────────────
  {
    slug: "furniture-assembly",
    name: "Furniture Assembly",
    category: "carpentry",
    description: "Professional assembly of flat-pack and modular furniture. All tools included, no mess left behind.",
    startingPrice: 279,
    rating: 4.8,
    reviewCount: 1234,
    duration: "1-2 hours",
    imageKey: "carpentry",
    popular: true,
  },
  {
    slug: "furniture-repair",
    name: "Furniture Repair",
    category: "carpentry",
    description: "Expert repair of wooden furniture including joints, hinges, drawers and structural damage.",
    startingPrice: 399,
    rating: 4.7,
    reviewCount: 643,
    duration: "1-2 hours",
    imageKey: "carpentry",
    popular: false,
  },
  {
    slug: "door-repair-fitting",
    name: "Door Repair / Fitting",
    category: "carpentry",
    description: "Repair and fitting of wooden and flush doors. Fixes sagging, squeaking, broken hinges and faulty locks.",
    startingPrice: 359,
    rating: 4.7,
    reviewCount: 876,
    duration: "1-2 hours",
    imageKey: "carpentry",
    popular: true,
  },
  {
    slug: "window-repair",
    name: "Window Repair",
    category: "carpentry",
    description: "Repair of wooden and aluminium windows including frame, pane, hinges and sealing for weatherproofing.",
    startingPrice: 319,
    rating: 4.6,
    reviewCount: 432,
    duration: "1-2 hours",
    imageKey: "carpentry",
    popular: false,
  },
  {
    slug: "wardrobe-installation",
    name: "Wardrobe Installation",
    category: "carpentry",
    description: "Installation of modular or hinged wardrobes with precise fitting, shelf placement and door alignment.",
    startingPrice: 799,
    rating: 4.8,
    reviewCount: 543,
    duration: "2-4 hours",
    imageKey: "carpentry",
    popular: false,
  },
  {
    slug: "bed-repair",
    name: "Bed Repair",
    category: "carpentry",
    description: "Repair of wooden bed frames including broken slats, loose joints, headboard and storage mechanisms.",
    startingPrice: 479,
    rating: 4.7,
    reviewCount: 321,
    duration: "1-2 hours",
    imageKey: "carpentry",
    popular: false,
  },
  {
    slug: "wood-polishing-furniture",
    name: "Wood Polishing (Furniture)",
    category: "carpentry",
    description: "Restore furniture shine with professional wood polishing, sanding and lacquer or PU finish application.",
    startingPrice: 639,
    rating: 4.7,
    reviewCount: 456,
    duration: "2-3 hours",
    imageKey: "carpentry",
    popular: false,
  },
  {
    slug: "sofa-frame-repair",
    name: "Sofa Frame Repair",
    category: "carpentry",
    description: "Structural repair of wooden sofa frames including broken legs, sagging base and joint reinforcement.",
    startingPrice: 559,
    rating: 4.7,
    reviewCount: 287,
    duration: "1-2 hours",
    imageKey: "carpentry",
    popular: false,
  },

  // ── Appliance Repair (13) ──────────────────────────────────────────────────
  {
    slug: "ac-service-1ton",
    name: "AC Service (1 Ton)",
    category: "appliances",
    description: "Complete service for 1-ton AC including cleaning filters, coils, drainage and performance check.",
    startingPrice: 679,
    rating: 4.8,
    reviewCount: 2341,
    duration: "1-2 hours",
    imageKey: "appliances",
    popular: true,
  },
  {
    slug: "ac-service-15ton",
    name: "AC Service (1.5 Ton)",
    category: "appliances",
    description: "Complete service for 1.5-ton AC including deep cleaning, gas pressure check and cooling optimization.",
    startingPrice: 799,
    rating: 4.8,
    reviewCount: 1987,
    duration: "1-2 hours",
    imageKey: "appliances",
    popular: true,
  },
  {
    slug: "ac-gas-refill",
    name: "AC Gas Refill",
    category: "appliances",
    description: "AC refrigerant gas refill with leak check. Restores full cooling capacity and energy efficiency.",
    startingPrice: 1199,
    rating: 4.7,
    reviewCount: 1234,
    duration: "1-2 hours",
    imageKey: "appliances",
    popular: false,
  },
  {
    slug: "ac-installation",
    name: "AC Installation (1-1.5 Ton)",
    category: "appliances",
    description: "Professional split AC installation including bracket, copper pipe, drainage and electrical connections.",
    startingPrice: 1279,
    rating: 4.8,
    reviewCount: 876,
    duration: "2-3 hours",
    imageKey: "appliances",
    popular: false,
  },
  {
    slug: "washing-machine-repair",
    name: "Washing Machine Repair",
    category: "appliances",
    description: "Expert repair of all washing machine brands. Covers motor, drum, board, door latch and valve issues.",
    startingPrice: 399,
    rating: 4.7,
    reviewCount: 1234,
    duration: "1-2 hours",
    imageKey: "appliances",
    popular: true,
  },
  {
    slug: "refrigerator-repair",
    name: "Refrigerator Repair",
    category: "appliances",
    description: "Diagnosis and repair of all fridge brands. Covers compressor, thermostat, fan, door seal and gas issues.",
    startingPrice: 439,
    rating: 4.7,
    reviewCount: 987,
    duration: "1-2 hours",
    imageKey: "appliances",
    popular: false,
  },
  {
    slug: "microwave-repair",
    name: "Microwave Repair",
    category: "appliances",
    description: "Repair of microwave ovens covering magnetron, turntable, door latch and control board faults.",
    startingPrice: 359,
    rating: 4.6,
    reviewCount: 654,
    duration: "30-60 min",
    imageKey: "appliances",
    popular: false,
  },
  {
    slug: "tv-repair",
    name: "TV Repair",
    category: "appliances",
    description: "Diagnosis and repair of LED, LCD and Smart TVs. Covers screen, board, backlight and HDMI port issues.",
    startingPrice: 479,
    rating: 4.6,
    reviewCount: 765,
    duration: "1-2 hours",
    imageKey: "appliances",
    popular: false,
  },
  {
    slug: "appliance-geyser-repair",
    name: "Geyser Repair",
    category: "appliances",
    description: "Repair of electric and gas geysers covering heating element, thermostat, valve and pilot light issues.",
    startingPrice: 399,
    rating: 4.7,
    reviewCount: 543,
    duration: "1-2 hours",
    imageKey: "appliances",
    popular: false,
  },
  {
    slug: "dishwasher-repair",
    name: "Dishwasher Repair",
    category: "appliances",
    description: "Repair of all dishwasher brands covering pump, spray arm, door latch, control board and drainage.",
    startingPrice: 439,
    rating: 4.6,
    reviewCount: 312,
    duration: "1-2 hours",
    imageKey: "appliances",
    popular: false,
  },
  {
    slug: "chimney-cleaning-repair",
    name: "Chimney Cleaning & Repair",
    category: "appliances",
    description: "Deep cleaning of kitchen chimneys including filter, motor and duct. Restores full suction power.",
    startingPrice: 479,
    rating: 4.7,
    reviewCount: 876,
    duration: "1-2 hours",
    imageKey: "appliances",
    popular: true,
  },
  {
    slug: "treadmill-repair",
    name: "Treadmill Repair",
    category: "appliances",
    description: "Repair and servicing of treadmills covering belt, motor, console and incline mechanism issues.",
    startingPrice: 559,
    rating: 4.6,
    reviewCount: 234,
    duration: "1-2 hours",
    imageKey: "appliances",
    popular: false,
  },
  {
    slug: "inverter-ups-repair",
    name: "Inverter / UPS Repair",
    category: "appliances",
    description: "Diagnosis and repair of home inverters and UPS units covering battery, board and charging faults.",
    startingPrice: 399,
    rating: 4.7,
    reviewCount: 432,
    duration: "1-2 hours",
    imageKey: "appliances",
    popular: false,
  },

  // ── Water Purifier / RO (5) ────────────────────────────────────────────────
  {
    slug: "ro-service-filter-change",
    name: "RO Service & Filter Change",
    category: "water-purifier",
    description: "Comprehensive RO service including membrane check, all filter replacements and water quality testing.",
    startingPrice: 399,
    rating: 4.8,
    reviewCount: 1543,
    duration: "1-2 hours",
    imageKey: "plumbing",
    popular: true,
  },
  {
    slug: "ro-installation",
    name: "RO Installation",
    category: "water-purifier",
    description: "Professional under-sink or wall-mount RO purifier installation with proper plumbing and testing.",
    startingPrice: 679,
    rating: 4.8,
    reviewCount: 876,
    duration: "1-2 hours",
    imageKey: "plumbing",
    popular: true,
  },
  {
    slug: "ro-repair",
    name: "RO Repair",
    category: "water-purifier",
    description: "Diagnosis and repair of RO purifier faults including pump, membrane, solenoid valve and TDS issues.",
    startingPrice: 359,
    rating: 4.7,
    reviewCount: 654,
    duration: "1-2 hours",
    imageKey: "plumbing",
    popular: false,
  },
  {
    slug: "uv-purifier-service",
    name: "UV Purifier Service",
    category: "water-purifier",
    description: "Servicing of UV water purifiers including UV lamp replacement, filter cleaning and disinfection.",
    startingPrice: 319,
    rating: 4.7,
    reviewCount: 432,
    duration: "1 hour",
    imageKey: "plumbing",
    popular: false,
  },
  {
    slug: "water-softener-service",
    name: "Water Softener Service",
    category: "water-purifier",
    description: "Maintenance and servicing of water softeners including resin regeneration, valve check and salt refill.",
    startingPrice: 479,
    rating: 4.6,
    reviewCount: 198,
    duration: "1-2 hours",
    imageKey: "plumbing",
    popular: false,
  },
];

const PROVIDERS = [
  {
    slug: "rahul-sharma",
    name: "Rahul Sharma",
    initials: "RS",
    rating: 4.9,
    reviewCount: 342,
    jobsCompleted: 1256,
    specializations: ["Deep Cleaning", "Office Cleaning", "Move-in Cleaning"],
    experience: "5 years",
    verified: true,
    category: "cleaning",
  },
  {
    slug: "priya-patel",
    name: "Priya Patel",
    initials: "PP",
    rating: 4.8,
    reviewCount: 289,
    jobsCompleted: 987,
    specializations: ["Haircut", "Facial", "Manicure"],
    experience: "4 years",
    verified: true,
    category: "salon-women",
  },
  {
    slug: "amit-kumar",
    name: "Amit Kumar",
    initials: "AK",
    rating: 4.9,
    reviewCount: 412,
    jobsCompleted: 1589,
    specializations: ["Pipe Repair", "Drain Cleaning", "Bathroom Fitting"],
    experience: "7 years",
    verified: true,
    category: "plumbing",
  },
  {
    slug: "sunita-devi",
    name: "Sunita Devi",
    initials: "SD",
    rating: 4.7,
    reviewCount: 178,
    jobsCompleted: 634,
    specializations: ["Home Cleaning", "Kitchen Deep Clean"],
    experience: "3 years",
    verified: true,
    category: "cleaning",
  },
  {
    slug: "vikram-singh",
    name: "Vikram Singh",
    initials: "VS",
    rating: 4.8,
    reviewCount: 267,
    jobsCompleted: 892,
    specializations: ["Wiring", "Fan Installation", "Switch Repair"],
    experience: "6 years",
    verified: true,
    category: "electrical",
  },
  {
    slug: "meena-joshi",
    name: "Meena Joshi",
    initials: "MJ",
    rating: 4.9,
    reviewCount: 198,
    jobsCompleted: 723,
    specializations: ["Facial", "Hair Color", "Waxing"],
    experience: "5 years",
    verified: true,
    category: "salon-women",
  },
  {
    slug: "raju-electrician",
    name: "Raju Verma",
    initials: "RV",
    rating: 4.8,
    reviewCount: 321,
    jobsCompleted: 1102,
    specializations: ["AC Repair", "Wiring", "MCB Fitting"],
    experience: "8 years",
    verified: true,
    category: "electrical",
  },
  {
    slug: "deepak-plumber",
    name: "Deepak Nair",
    initials: "DN",
    rating: 4.7,
    reviewCount: 234,
    jobsCompleted: 867,
    specializations: ["Water Heater", "Tap Repair", "Drain Cleaning"],
    experience: "4 years",
    verified: true,
    category: "plumbing",
  },
  // New providers for salon-men, massage, water-purifier
  {
    slug: "arjun-barber",
    name: "Arjun Mehta",
    initials: "AM",
    rating: 4.8,
    reviewCount: 312,
    jobsCompleted: 945,
    specializations: ["Haircut", "Beard Grooming", "Hair Color"],
    experience: "5 years",
    verified: true,
    category: "salon-men",
  },
  {
    slug: "kavita-barber",
    name: "Kavita Sharma",
    initials: "KS",
    rating: 4.7,
    reviewCount: 198,
    jobsCompleted: 623,
    specializations: ["Haircut", "Head Massage", "Detan"],
    experience: "3 years",
    verified: true,
    category: "salon-men",
  },
  {
    slug: "neha-therapist",
    name: "Neha Gupta",
    initials: "NG",
    rating: 4.9,
    reviewCount: 287,
    jobsCompleted: 812,
    specializations: ["Swedish Massage", "Deep Tissue", "Foot Reflexology"],
    experience: "6 years",
    verified: true,
    category: "massage",
  },
  {
    slug: "suresh-therapist",
    name: "Suresh Pillai",
    initials: "SP",
    rating: 4.8,
    reviewCount: 234,
    jobsCompleted: 678,
    specializations: ["Deep Tissue Massage", "Couple Massage", "Head Massage"],
    experience: "7 years",
    verified: true,
    category: "massage",
  },
  {
    slug: "rajesh-ro",
    name: "Rajesh Iyer",
    initials: "RI",
    rating: 4.8,
    reviewCount: 312,
    jobsCompleted: 1043,
    specializations: ["RO Installation", "RO Repair", "UV Purifier Service"],
    experience: "6 years",
    verified: true,
    category: "water-purifier",
  },
  {
    slug: "mohan-ro",
    name: "Mohan Das",
    initials: "MD",
    rating: 4.7,
    reviewCount: 187,
    jobsCompleted: 567,
    specializations: ["RO Service", "Water Softener", "Filter Change"],
    experience: "4 years",
    verified: true,
    category: "water-purifier",
  },
];

export async function seedDatabase() {
  try {
    logger.info("Seeding database — replacing service catalog...");

    await db.delete(servicesTable);
    await db.insert(servicesTable).values(SERVICES);
    logger.info(`Seeded ${SERVICES.length} services`);

    await db
      .insert(providersTable)
      .values(PROVIDERS)
      .onConflictDoUpdate({
        target: providersTable.slug,
        set: { category: sql`excluded.category` },
      });
    logger.info(`Upserted sample providers (category migrations applied)`);

    const existingNotifs = await db
      .select()
      .from(notificationsTable)
      .where(eq(notificationsTable.userId, USER_ID))
      .limit(1);

    if (existingNotifs.length === 0) {
      await db.insert(notificationsTable).values([
        {
          userId: USER_ID,
          type: "welcome",
          icon: "gift",
          iconColor: "#f97316",
          title: "Welcome to Ultrofix!",
          body: "Book your first service and get 20% off. Use code: FIRST20",
          read: false,
        },
        {
          userId: USER_ID,
          type: "offer",
          icon: "tag",
          iconColor: "#8b5cf6",
          title: "Special Weekend Offer",
          body: "Get 30% off on all cleaning services this weekend. Limited time only!",
          read: false,
        },
      ]);
      logger.info("Default notifications seeded");
    }
  } catch (err) {
    logger.error({ err }, "Failed to seed database");
  }
}
